name: ESBMC verification action
description: Verifies single- and multithreaded C/C++, CUDA, CHERI, Kotlin, Python, and Solidity programs using the ESBMC.

inputs:
  esbmc-options:
    description: Options to be used with ESBMC
    required: false
    default: "--incremental-bmc --quiet --smt-model --color --verbosity 4"

runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    

    - name: Get Git Diff
      id: get-diff
      run: |
        echo "FILE_DIFF<<EOF" >> $GITHUB_ENV
        echo "$(git diff --name-only --diff-filter=ACMR HEAD HEAD^ | grep -E '\.c|\.cpp')" >> "$GITHUB_ENV"
        echo "EOF" >> $GITHUB_ENV
      shell: bash
    
    - run: |
        echo $'\n'
        echo "----------------------------------------------------"
        echo "No git diff in files of the correct type have been detected."
      shell: bash
      if: ${{ env.FILE_DIFF == '' }}
    


    - name: Install ESBMC Linux
      run: |
        sudo apt update && sudo apt install wget
        wget -O esbmc.zip https://github.com/esbmc/esbmc/releases/download/v7.6.1/release-ubuntu-latest.zip
        unzip -o -q esbmc.zip
        chmod +x $GITHUB_WORKSPACE/bin/esbmc
      shell: bash
      if: ${{ env.FILE_DIFF != '' && runner.os == 'Linux' }}
    
    - name: Run ESBMC Linux
      run: |
        while IFS= read -r path || [[ -n $path ]]
        do
          echo $'\n'
          echo "----------------------------------------------------"
          echo $'\n'
          echo "Running ESBMC on $path"
          $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} "$path" || true
        done < <(printf '%s' "${{ env.FILE_DIFF }}")
        echo $'\n'
        echo "----------------------------------------------------"
        echo "Finished verifying files."
      shell: bash
      if: ${{ env.FILE_DIFF != '' && runner.os == 'Linux' }}



    - name: Install ESBMC macOS
      run: |
        brew install wget boost
        wget -O esbmc.zip https://github.com/esbmc/esbmc/releases/download/v7.6/release-macos-latest.zip
        unzip -o -q esbmc.zip
        chmod +x $GITHUB_WORKSPACE/bin/esbmc
      shell: bash
      if: ${{ env.FILE_DIFF != '' && runner.os == 'macOS' }}
    
    - name: Run ESBMC macOS
      run: |
        while IFS= read -r path || [[ -n $path ]]
        do
          echo $'\n'
          echo "----------------------------------------------------"
          echo $'\n'
          echo "Running ESBMC on $path"
          $GITHUB_WORKSPACE/bin/esbmc --smtlib --smt-formula-only ${{ inputs.esbmc-options }} "$path" || true
        done < <(printf '%s' "${{ env.FILE_DIFF }}")
        echo $'\n'
        echo "----------------------------------------------------"
        echo "Finished verifying files."
      shell: bash
      if: ${{ env.FILE_DIFF != '' && runner.os == 'macOS' }}
    


    - name: Install ESBMC Windows
      run: |
        $client = new-object System.Net.WebClient
        $client.DownloadFile("https://github.com/esbmc/esbmc/releases/download/v7.6.1/release-windows-latest.zip", "$env:GITHUB_WORKSPACE\esbmc.zip")
        unzip -o -q esbmc.zip
        chmod +x $env:GITHUB_WORKSPACE/bin/esbmc
      shell: powershell
      if: ${{ env.FILE_DIFF != '' && runner.os == 'Windows' }}
    
    - name: Run ESBMC Windows
      run: |
        while IFS= read -r path || [[ -n $path ]]
        do
          echo $'\n'
          echo "----------------------------------------------------"
          echo $'\n'
          echo "Running ESBMC on $path"
          $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} "$path" || true
        done < <(printf '%s' "${{ env.FILE_DIFF }}")
        echo $'\n'
        echo "----------------------------------------------------"
        echo "Finished verifying files."
      shell: bash
      if: ${{ env.FILE_DIFF != '' && runner.os == 'Windows' }}