name: ESBMC verification action
description: Verifies single- and multithreaded C/C++, CUDA, CHERI, Kotlin, Python, and Solidity programs using the ESBMC.

inputs:
  esbmc-options:
    description: Options to be used with ESBMC
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Get Diff Action
      id: get-diff
      uses: technote-space/get-diff-action@v6.1.2
      with:
        DIFF_FILTER: ACMR
        ABSOLUTE: false
        PATTERNS: "**/*@(.c|.cpp|.cu|.kt|.kts|.py|.sol)"
    
    - name: Install ESBMC
      run: |
        sudo apt update && sudo apt install wget
        wget -O esbmc.zip https://github.com/esbmc/esbmc/releases/download/v7.6.1/release-ubuntu-latest.zip
        unzip -o esbmc.zip
        chmod +x ./bin/esbmc
      shell: bash
      if: ${{ steps.get-diff.outputs.diff != '' }}

    - name: Run ESBMC
      run: |
        readarray -d ' ' -t pathArr < ${{ steps.get-diff.outputs.diff }}
        for path in "${pathArr[@]}"
        do
          $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} $path
        done
      shell: bash
      if: ${{ steps.get-diff.outputs.diff != '' }}