name: ESBMC verification action
description: Verifies single- and multithreaded C/C++, CUDA, CHERI, Kotlin, Python, and Solidity programs using the ESBMC.

runs:
  using: 'composite'
  steps:
    - name: Get Diff Action
      id: get-diff
      uses: technote-space/get-diff-action@v6.1.2
      with:
        DIFF_FILTER: ACMR
        ABSOLUTE: true
        PATTERNS: "*@(.c|.cpp|.cu|.kt|.kts|.py|.sol)"

    - run: readarray -d ' ' -t pathArr < <(${{ steps.get-diff.outputs.diff }}) &&
           for path in "${pathArr[@]}"
           do
             esbmc path
           done
      shell: bash
      continue-on-error: false