name: ESBMC verification action
description: Verifies single- and multithreaded C/C++, CUDA, CHERI, Kotlin, Python, and Solidity programs using the ESBMC.

inputs:
  esbmc-options:
    description: Options to be used with ESBMC
    required: false
    default: "--incremental-bmc"

runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    

    - name: Get Git Diff
      id: get-diff
      run: echo "diff=$(git diff --name-only --diff-filter=ACMR HEAD HEAD^ | grep -E '\.c|\.cpp')" >> "$GITHUB_OUTPUT"
      shell: bash
    
    - run: echo "No changes in files of the correct type have been detected."
      shell: bash
      if: ${{ steps.get-diff.outputs.diff == '' }}
    

    - name: Install ESBMC Linux
      run: |
        sudo apt update && sudo apt install wget
        wget -O esbmc.zip https://github.com/esbmc/esbmc/releases/download/v7.6.1/release-ubuntu-latest.zip
        unzip -o esbmc.zip
        chmod +x $GITHUB_WORSKPACE/bin/esbmc
      shell: bash
      if: ${{ steps.get-diff.outputs.diff != '' && runner.os == 'Linux' }}
    
    - name: Run ESBMC Linux
      run: |
        for path in ${{ steps.get-diff.outputs.diff }}
        do
          $GITHUB_WORKSPACE/bin/esbmc ${{ inputs.esbmc-options }} $path
        done
        echo "Finished verifying files."
      shell: bash
      if: ${{ steps.get-diff.outputs.diff != '' && runner.os == 'Linux' }}


    - name: Install ESBMC macOS
      run: |
        brew install wget boost
        wget -O esbmc.zip https://github.com/esbmc/esbmc/releases/download/v7.6/release-macos-latest.zip
        unzip -o esbmc.zip
        chmod +x $GITHUB_WORKSPACE/bin/esbmc
      shell: bash
      if: ${{ steps.get-diff.outputs.diff != '' && runner.os == 'macOS' }}
    
    - name: Run ESBMC macOS
      run: |
        for path in ${{ steps.get-diff.outputs.diff }}
        do
          $GITHUB_WORKSPACE/bin/esbmc --smtlib --smt-formula-only ${{ inputs.esbmc-options }} $path
        done
        echo "Finished verifying files."
      shell: bash
      if: ${{ steps.get-diff.outputs.diff != '' && runner.os == 'macOS' }}